{% set name = "blue" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/blue-{{ version }}.tar.gz
  sha256: 76b4f26884a8425042356601d80773db6e0e14bebaa7a59d7c54bf8cef2e2af5

build:
  entry_points:
    - blue=blue:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - black ==22.1.0
    - flake8 >=3.8,<5.0.0
    - python >={{ python_min }}

test:
  imports:
    - blue
  commands:
    - pip check
    - blue --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://iblueit.dev/
  summary: The slightly less uncompromising Python code formatter.
  dev_url: https://github.com/grantjenks/blue.git
  doc_url: https://blue.readthedocs.io/en/latest/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
